// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syothuxkimavlcdhzklo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5b3RodXhraW1hdmxjZGh6a2xvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzMwNjcsImV4cCI6MjA2MDgwOTA2N30.xoZjlFuXrAycpi4gjAak6y0Orag6n_J1lCpTIyoO7J4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);